# Generated by Django 5.1.1 on 2024-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_task_created_at_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('user_story', 'User Story'), ('technical_task', 'Technical Task')], default='user_story', max_length=50),
        ),
    ]
