# Generated by Django 5.1.1 on 2024-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_contact_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='tasks_as_member', to='todo_list.contact'),
        ),
    ]
