# Generated by Django 5.1.1 on 2024-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_contact_color'),
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='tasks_as_member', to='user_auth_app.userprofile'),
        ),
    ]
