# Generated by Django 5.1.1 on 2024-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0011_alter_subtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks_progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
