# Generated by Django 5.1.1 on 2024-11-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0013_remove_subtask_task_subtask_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_id',
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo_list.task'),
        ),
    ]
